// Generated by CoffeeScript 2.3.1
(function() {
  module.exports = {
    misfit: Symbol('misfit'),
    last: Symbol('last'),
    surround: Symbol('surround'),
    end: Symbol('end')
  };

}).call(this);

//# sourceMappingURL=_symbols.js.map
