// Generated by CoffeeScript 2.3.1
(function() {
  //###########################################################################################################
  var $, $async, $send_three, CND, PS, after, badge, debug, echo, help, include, info, jr, rpr, test, urge, warn, whisper,
    indexOf = [].indexOf;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'PIPESTREAMS/TESTS/ASYNC-MAP';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  test = require('guy-test');

  jr = JSON.stringify;

  //...........................................................................................................
  PS = require('../..');

  ({$, $async} = PS);

  //-----------------------------------------------------------------------------------------------------------
  after = function(dts, f) {
    return setTimeout(f, dts * 1000);
  };

  //-----------------------------------------------------------------------------------------------------------
  this._prune = function() {
    var name, ref, value;
    ref = this;
    for (name in ref) {
      value = ref[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._main = function() {
    return test(this, {
      'timeout': 30000
    });
  };

  //===========================================================================================================

  // #-----------------------------------------------------------------------------------------------------------
  // @[ "async 1" ] = ( T, done ) ->
  //   ok        = false
  //   probe     = "abcdef"
  //   matcher   =  "*a**b**c**d**e**f*"
  //   pipeline  = []
  //   pipeline.push PS.new_value_source Array.from probe
  //   pipeline.push PS._$async_map ( d, handler ) ->
  //     after ( Math.random() / 5 ), ->
  //       handler null, '*' + d + '*'
  //     return null
  //   pipeline.push PS.$show()
  //   pipeline.push PS.$join()
  //   #.........................................................................................................
  //   pipeline.push PS.$watch ( result ) ->
  //     echo CND.gold jr [ probe, result, ]
  //     T.eq result, matcher
  //     ok = true
  //   #.........................................................................................................
  //   pipeline.push PS.$drain ->
  //     T.fail "failed to pass test" unless ok
  //     done()
  //   #.........................................................................................................
  //   PS.pull pipeline...
  //   return null

  // #-----------------------------------------------------------------------------------------------------------
  // @[ "async 1 paramap" ] = ( T, done ) ->
  //   ok        = false
  //   probe     = "abcdef"
  //   matcher   =  "*a**b**c**d**e**f*"
  //   pipeline  = []
  //   pipeline.push PS.new_value_source Array.from probe
  //   pipeline.push PS._$paramap ( d, handler ) ->
  //     after ( Math.random() / 5 ), ->
  //       handler null, '*' + d + '*'
  //     return null
  //   pipeline.push PS.$show()
  //   pipeline.push PS.$join()
  //   #.........................................................................................................
  //   pipeline.push PS.$watch ( result ) ->
  //     echo CND.gold jr [ probe, result, ]
  //     T.eq result, matcher
  //     ok = true
  //   #.........................................................................................................
  //   pipeline.push PS.$drain ->
  //     T.fail "failed to pass test" unless ok
  //     done()
  //   #.........................................................................................................
  //   PS.pull pipeline...
  //   return null

  //-----------------------------------------------------------------------------------------------------------
  $send_three = function() {
    return PS.$async(function(d, send, done) {
      var count, n;
      count = 0;
      n = 3;
      after(Math.random() / 5, function() {
        var i, nr, ref, results;
        debug('77634', d);
        results = [];
        for (nr = i = 1, ref = n; (1 <= ref ? i <= ref : i >= ref); nr = 1 <= ref ? ++i : --i) {
          count += +1;
          send(`(${d}:${nr})`);
          if (count >= n) {
            results.push(done());
          } else {
            results.push(void 0);
          }
        }
        return results;
      });
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this["async 2"] = function(T, done) {
    var matcher, ok, pipeline, probe;
    ok = false;
    probe = "abcdef";
    matcher = "(a:1)(a:2)(a:3)(b:1)(b:2)(b:3)(c:1)(c:2)(c:3)(d:1)(d:2)(d:3)(e:1)(e:2)(e:3)(f:1)(f:2)(f:3)";
    pipeline = [];
    pipeline.push(PS.new_value_source(Array.from(probe)));
    pipeline.push($send_three());
    pipeline.push(PS.$show());
    pipeline.push(PS.$join());
    //.........................................................................................................
    pipeline.push(PS.$watch(function(result) {
      echo(CND.gold(jr([probe, result])));
      T.eq(result, matcher);
      return ok = true;
    }));
    //.........................................................................................................
    pipeline.push(PS.$drain(function() {
      if (!ok) {
        T.fail("failed to pass test");
      }
      return done();
    }));
    //.........................................................................................................
    PS.pull(...pipeline);
    return null;
  };

  //###########################################################################################################
  if (module.parent == null) {
    include = ["async 1", "async 1 paramap", "async 2"];
    this._prune();
    this._main();
  }

}).call(this);

//# sourceMappingURL=async-map.test.js.map
