// Generated by CoffeeScript 1.11.1
(function() {
  var $, $async, CND, FS, OS, PATH, PS, alert, badge, debug, echo, help, info, log, rpr, tap, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'PIPESTREAMS/TESTS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  PATH = require('path');

  FS = require('fs');

  OS = require('os');

  tap = require('tap');

  PS = require('../..');

  $ = PS.$, $async = PS.$async;

  tap.test("test line assembler", function(T) {
    var assembler, chunk, chunks, collector, i, len, text;
    text = "\"　2. 纯；专：专～。～心～意。\"\n!\"　3. 全；满：～生。～地水。\"\n\"　4. 相同：～样。颜色不～。\"\n\"　5. 另外!的：蟋蟀～名促织。!\"\n\"　6. 表示动作短暂，或是一次，或具试探性：算～算。试～试。\"!\n\"　7. 乃；竞：～至于此。\"";
    chunks = text.split('!');
    text = text.replace(/!/g, '');
    collector = [];
    assembler = PS._new_line_assembler({
      extra: true,
      splitter: '\n'
    }, function(error, line) {
      if (error != null) {
        throw error;
      }
      if (line != null) {
        collector.push(line);
        return info(rpr(line));
      } else {
        if (CND.equals(text, collector.join('\n'))) {
          T.pass("texts are equal");
        }
        return T.end();
      }
    });
    for (i = 0, len = chunks.length; i < len; i++) {
      chunk = chunks[i];
      assembler(chunk);
    }
    return assembler(null);
  });

  tap.test('test throughput', function(T) {
    var input, lines, output;
    input = PS.new_stream(PATH.resolve(__dirname, '../../test-data/Unicode-NamesList.txt'));
    output = FS.createWriteStream('/tmp/output.txt');
    lines = [];
    input.pipe(PS.$split()).pipe(PS.$pass()).pipe(PS.$as_line()).pipe($(function(line, send) {
      lines.push(line);
      return send(line);
    })).pipe(output);

    /* TAINT use PipeStreams method */
    input.on('end', function() {
      return output.end();
    });
    output.on('close', function() {
      T.pass("assuming equality");
      return T.end();
    });
    return null;
  });

}).call(this);

//# sourceMappingURL=basic.js.map
